version: "3.9"
    
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    build:
      context: ./
      dockerfile: ./Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    
  comcat:
    image: tomcat:9.0.64-jre8-temurin-focal
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8888:8080"
    restart: always
